### ISSUE TITLE
Raise issue with protected characters

### ISSUE THREAD

**Issue by m-priestley** [jonpecar/qrCodeImageSorterGUI#12]
it would be good if the program can flag issues with QR labels that contain protected characters that cant be in windows folder names 

i.e. any of these \ / : * ? < > | 

QR codes with these charcaters fails to create the folder and puts the photos into unsorted

I think the most simple solution is to not let them be created in the first instance and for the program to output an error showing the lines in the GUI that are affected with labels that contain the above characters

**Comment by jonpecar** [comment]
I will implement a warning when generating QR codes to alert the user to invalid characters being present. I have also raised an issue in the base library to automatically clean file paths so that images can still be sorted if there are invalid characters present: [https://github.com/jonpecar/qrCodeImageSorter/issues/38](https://github.com/jonpecar/qrCodeImageSorter/issues/38)

**Comment by jonpecar** [comment]
Warning is now implemented
